version: '3.8'
services:

  php-apache-environment:
    container_name: blog
    image: hobotest:latest
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - my_vol:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
volumes:
  my_vol: